
resources:
# By setting the radicle-ci repo as a resource, concourse will monitor it and trigger new builds
# e.g. when it sees new commits - more details: https://concourse-ci.org/resources.html
- name: repo
  type: git
  source:
    uri: https://radicle.yorgos.net.gr/zBNXLtTqUu9LBZHCPFShAeXnp5Gz.git
    branch: ((patch_branch))

jobs:
- name: cargo-test-job
  plan:
    # checkout the code from the repo
    - get: repo
      trigger: true # tell Concourse to trigger this job when new versions are emitted

    # run cargo build
    - task: cargo-test-all
      config:
        platform: linux
        image_resource:
          type: registry-image
          source:
            repository: quay.io/gsaslis/rust-git-builder # built from https://github.com/gsaslis/rust-git-builder/blob/main/Dockerfile
            tag: latest
        inputs:
          - name: repo
        outputs:
          - name: output.txt
        run:
          dir: repo
          path: /bin/bash
          args:
            - -c
            - |
              git --version
              . "$HOME/.cargo/env"
              cargo --version

              # run tests
              RUST_BACKTRACE=1 cargo test --all | tee output.txt
